IWD
gdgbaroda/gdgbaroda.github.io pull request #19
Opened 2018-07-19 17:59 UTC by harshpopat

File has been uploaded

2018-07-19 18:01 UTC, mistryhardik commented on _posts/2018-07-19-IWD.md
> +#### Speaker: Saurabhi Jain
The name is **Surbhi Jain**.

2018-07-20 03:43 UTC, manan-jadhav requested changes

2018-07-20 03:43 UTC, CurosMJ commented on _posts/2018-07-19-IWD.md
> +
add some more content here, explain when this was, where it was, who organised (WTM)

2018-07-20 03:43 UTC, CurosMJ commented on _posts/2018-07-19-IWD.md
> +
add some images please

2018-07-21 05:07 UTC, CurosMJ commented
Please add more descriptive PR title and description

2018-07-21 05:08 UTC, CurosMJ commented
You have created a new file instead of changing the existing one, please correct this as well.

2018-07-21 11:58 UTC, manan-jadhav requested changes

2018-07-21 11:58 UTC, CurosMJ commented on _posts/2018-07-21-IWD.md
> +![IWD](https://scontent.fbdq1-1.fna.fbcdn.net/v/t1.0-9/30572137_951380235031037_4460753643510956032_n.jpg?_nc_cat=0&oh=0e09ffe70e44653aaddfc710f3f796ca&oe=5BCCDC63)
Please download the images in the assets folder and use from there. These links can expire anytime.

2018-07-21 11:58 UTC, CurosMJ commented on _posts/2018-07-21-IWD.md
> +A fabulous event organized by **WTM(Women Techmakers) held on 8th April 2018** was all about how far women have reached, where they are falling behind and how perceptions continue to shift. It was on
Please mention WTM Baroda

2018-07-21 14:29 UTC, harshpopat commented
Ok I'll do it, any further changes?

On Sat 21 Jul, 2018, 5:28 PM Manan Jadhav, <notifications@github.com> wrote:

> *@CurosMJ* requested changes on this pull request.
> ------------------------------
>
> In _posts/2018-07-21-IWD.md
> <https://github.com/gdgbaroda/gdgbaroda.github.io/pull/19#discussion_r204209179>
> :
>
> > @@ -0,0 +1,51 @@
> +# International Women's Day (IWD)
> +
> +A fabulous event organized by **WTM(Women Techmakers) held on 8th April 2018** was all about how far women have reached, where they are falling behind and how perceptions continue to shift. It was one of the memorable meets of [GDG Baroda](https://www.meetup.com/gdgbaroda/) to empower women.
> +
> +![IWD](https://scontent.fbdq1-1.fna.fbcdn.net/v/t1.0-9/30572137_951380235031037_4460753643510956032_n.jpg?_nc_cat=0&oh=0e09ffe70e44653aaddfc710f3f796ca&oe=5BCCDC63)
>
> Please download the images in the assets folder and use from there. These
> links can expire anytime.
> ------------------------------
>
> In _posts/2018-07-21-IWD.md
> <https://github.com/gdgbaroda/gdgbaroda.github.io/pull/19#discussion_r204209182>
> :
>
> > @@ -0,0 +1,51 @@
> +# International Women's Day (IWD)
> +
> +A fabulous event organized by **WTM(Women Techmakers) held on 8th April 2018** was all about how far women have reached, where they are falling behind and how perceptions continue to shift. It was one of the memorable meets of [GDG Baroda](https://www.meetup.com/gdgbaroda/) to empower women.
>
> Please mention WTM Baroda
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gdgbaroda/gdgbaroda.github.io/pull/19#pullrequestreview-139256438>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AX6dkndu0LZnLKdb2nzoWcWC_h0Bh3SLks5uIxdsgaJpZM4VW1zq>
> .
>

2018-07-21 14:43 UTC, harshpopat commented
In the asset folder the images are of only tensorflow not IWD.

On Sat 21 Jul, 2018, 7:58 PM Harsh Popat, <harshpopat75@gmail.com> wrote:

> Ok I'll do it, any further changes?
>
> On Sat 21 Jul, 2018, 5:28 PM Manan Jadhav, <notifications@github.com>
> wrote:
>
>> *@CurosMJ* requested changes on this pull request.
>> ------------------------------
>>
>> In _posts/2018-07-21-IWD.md
>> <https://github.com/gdgbaroda/gdgbaroda.github.io/pull/19#discussion_r204209179>
>> :
>>
>> > @@ -0,0 +1,51 @@
>> +# International Women's Day (IWD)
>> +
>> +A fabulous event organized by **WTM(Women Techmakers) held on 8th April 2018** was all about how far women have reached, where they are falling behind and how perceptions continue to shift. It was one of the memorable meets of [GDG Baroda](https://www.meetup.com/gdgbaroda/) to empower women.
>> +
>> +![IWD](https://scontent.fbdq1-1.fna.fbcdn.net/v/t1.0-9/30572137_951380235031037_4460753643510956032_n.jpg?_nc_cat=0&oh=0e09ffe70e44653aaddfc710f3f796ca&oe=5BCCDC63)
>>
>> Please download the images in the assets folder and use from there. These
>> links can expire anytime.
>> ------------------------------
>>
>> In _posts/2018-07-21-IWD.md
>> <https://github.com/gdgbaroda/gdgbaroda.github.io/pull/19#discussion_r204209182>
>> :
>>
>> > @@ -0,0 +1,51 @@
>> +# International Women's Day (IWD)
>> +
>> +A fabulous event organized by **WTM(Women Techmakers) held on 8th April 2018** was all about how far women have reached, where they are falling behind and how perceptions continue to shift. It was one of the memorable meets of [GDG Baroda](https://www.meetup.com/gdgbaroda/) to empower women.
>>
>> Please mention WTM Baroda
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/gdgbaroda/gdgbaroda.github.io/pull/19#pullrequestreview-139256438>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AX6dkndu0LZnLKdb2nzoWcWC_h0Bh3SLks5uIxdsgaJpZM4VW1zq>
>> .
>>
>

2018-07-21 14:55 UTC, harshpopat commented
Ok bro I'll download in asset and then use it

On Sat 21 Jul, 2018, 8:13 PM Harsh Popat, <harshpopat75@gmail.com> wrote:

> In the asset folder the images are of only tensorflow not IWD.
>
> On Sat 21 Jul, 2018, 7:58 PM Harsh Popat, <harshpopat75@gmail.com> wrote:
>
>> Ok I'll do it, any further changes?
>>
>> On Sat 21 Jul, 2018, 5:28 PM Manan Jadhav, <notifications@github.com>
>> wrote:
>>
>>> *@CurosMJ* requested changes on this pull request.
>>> ------------------------------
>>>
>>> In _posts/2018-07-21-IWD.md
>>> <https://github.com/gdgbaroda/gdgbaroda.github.io/pull/19#discussion_r204209179>
>>> :
>>>
>>> > @@ -0,0 +1,51 @@
>>> +# International Women's Day (IWD)
>>> +
>>> +A fabulous event organized by **WTM(Women Techmakers) held on 8th April 2018** was all about how far women have reached, where they are falling behind and how perceptions continue to shift. It was one of the memorable meets of [GDG Baroda](https://www.meetup.com/gdgbaroda/) to empower women.
>>> +
>>> +![IWD](https://scontent.fbdq1-1.fna.fbcdn.net/v/t1.0-9/30572137_951380235031037_4460753643510956032_n.jpg?_nc_cat=0&oh=0e09ffe70e44653aaddfc710f3f796ca&oe=5BCCDC63)
>>>
>>> Please download the images in the assets folder and use from there.
>>> These links can expire anytime.
>>> ------------------------------
>>>
>>> In _posts/2018-07-21-IWD.md
>>> <https://github.com/gdgbaroda/gdgbaroda.github.io/pull/19#discussion_r204209182>
>>> :
>>>
>>> > @@ -0,0 +1,51 @@
>>> +# International Women's Day (IWD)
>>> +
>>> +A fabulous event organized by **WTM(Women Techmakers) held on 8th April 2018** was all about how far women have reached, where they are falling behind and how perceptions continue to shift. It was one of the memorable meets of [GDG Baroda](https://www.meetup.com/gdgbaroda/) to empower women.
>>>
>>> Please mention WTM Baroda
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/gdgbaroda/gdgbaroda.github.io/pull/19#pullrequestreview-139256438>,
>>> or mute the thread
>>> <https://github.com/notifications/unsubscribe-auth/AX6dkndu0LZnLKdb2nzoWcWC_h0Bh3SLks5uIxdsgaJpZM4VW1zq>
>>> .
>>>
>>

2018-07-22 15:16 UTC, closed without merging