Facebook comments feature and other fixes
gdgbaroda/gdgbaroda.github.io pull request #2
Opened 2017-02-19 17:46 UTC by sagarvora

Fixed responsiveness of disclaimer, added facebook comments support in posts and moderators for the same, custom CSS to remove transition from anchor tag.

2017-02-21 15:26 UTC, manan-jadhav requested changes
Please keep "All Posts" as is, dont change it to "Blog"

2017-02-21 15:26 UTC, CurosMJ commented on _includes/navbar.html
> +        <li><a href="#"><i class="fa fa-calendar"></i> Events</a></li>
Inexistent link, please remove.

2017-02-21 15:26 UTC, CurosMJ commented on _layouts/post.html
> +<!-- Begin Facebook SDK -->
Move this to the base layout please

2017-02-21 15:26 UTC, CurosMJ commented on _layouts/post.html
> +      <div class="fb-comments" data-href="http://gdgbaroda.com{{ page.url }}" data-numposts="4" data-width="100%"></div>
data-href is buggy

2017-02-21 15:27 UTC, sagarvora commented
Ok i'll make the changes

2017-02-21 15:32 UTC, sagarvora commented on _includes/navbar.html
> +        <li><a href="#"><i class="fa fa-calendar"></i> Events</a></li>
shall I design a functionality to show events separately or shall we keep it as a part of 'events' category in blog?

2017-02-22 07:59 UTC, CurosMJ commented on _includes/navbar.html
> +        <li><a href="#"><i class="fa fa-calendar"></i> Events</a></li>
We'll add stuff when we have enough content

2017-02-22 09:34 UTC, sagarvora commented
Hey! Are any more changes required?

2017-02-23 01:26 UTC, manan-jadhav approved these changes

2017-02-23 01:27 UTC, merged