Add Post IO meetup file
gdgbaroda/gdgbaroda.github.io pull request #34
Opened 2018-07-23 19:32 UTC by DarshilBhatt

2018-07-24 04:19 UTC, CurosMJ commented
Please read up the contribution guide first : https://github.com/gdgbaroda/gdgbaroda.github.io/blob/master/CONTRIBUTING.md#writing-pull-requests

2018-07-24 04:41 UTC, DarshilBhatt commented
I've already read. Can you please tell me what's the issue exactly?

On 24 Jul 2018 9:49 a.m., "Manan Jadhav" <notifications@github.com> wrote:

> Please read up the contribution guide first :
> https://github.com/gdgbaroda/gdgbaroda.github.io/blob/
> master/CONTRIBUTING.md#writing-pull-requests
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gdgbaroda/gdgbaroda.github.io/pull/34#issuecomment-407276141>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AfE7PDPY2kPgxn0tBDu1XZA5RWkdyoERks5uJqBbgaJpZM4VbkYG>
> .
>

2018-07-24 04:59 UTC, knightkill commented
@DarshilBhatt 
You have to comment the changes while creating "New Pull request" follow this format:

What does this PR add / remove or fix?

Your answer here

Does this PR match the guidelines documented in the Contributing Guide?

Yes/No

2018-07-24 07:16 UTC, DarshilBhatt commented
Done

On 24 Jul 2018 10:29 a.m., "Hardip Patel" <notifications@github.com> wrote:

> @DarshilBhatt <https://github.com/DarshilBhatt>
> You have to comment the changes while creating "New Pull request" follow
> this format:
>
> What does this PR add / remove or fix?
>
> Your answer here
>
> Does this PR match the guidelines documented in the Contributing Guide?
>
> Yes/No
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gdgbaroda/gdgbaroda.github.io/pull/34#issuecomment-407281512>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AfE7PISy1LE4g59GDFBVQ7kdD1Ag5Ocpks5uJqmtgaJpZM4VbkYG>
> .
>

2018-07-25 02:40 UTC, manan-jadhav requested changes

2018-07-25 02:40 UTC, CurosMJ commented on _posts/2018-07-24-post-io-meetup.md
> + Countdown for Google IO conference began. Google IO is a three days event. At the first day in morning, they did breakfast at IO venue which was little bit strange for them but they told it was so g
Please break this into two paragraphs. Read "Updating PRs" sections of the contributing guide to see how to make updates to a PR.

2018-07-25 11:32 UTC, DarshilBhatt commented
Requested changes made.

On Wed, Jul 25, 2018 at 8:10 AM, Manan Jadhav <notifications@github.com>
wrote:

> *@CurosMJ* requested changes on this pull request.
> ------------------------------
>
> In _posts/2018-07-24-post-io-meetup.md
> <https://github.com/gdgbaroda/gdgbaroda.github.io/pull/34#discussion_r204967063>
> :
>
> > +layout: post
> +title: "Post IO Meetup"
> +date: 2018-07-24
> +categories: ["Events"]
> +tags: ["Google IO", "IO 2018"]
> +author: Darshil Bhatt
> +assets: "/assets/2018-07/post-io-meetup"
> +---
> +
> +After enjoying awesome event of Google IO Extended, co-organizers of [GDG Baroda](https://gdgbaroda.com/) who actually attended [Google IO](https://events.google.com/io/) at Shoreline, planned another meetup named Post IO meetup, just to share their great experience of Google IO conference. Just like every time, we're excited when we got confirmation from GDG Baroda for this meetup. Attendees were curious to know the experience of GDG Baroda co-organizers at Google IO, because to attend Google IO is like a dream for every developer and Google enthusiast.
> +
> +![Meetup about to begin!]({{page.assets}}/post_io.jpg){:class="img-responsive" : .center-image :height="400px" width="500px"}
> +
> +Finally the day came, meetup began in the rocking way! So, when two co-oragnizers, [Sneh Pandya](https://twitter.com/SnehPandya18) & [Manan Jadhav](https://twitter.com/curosmj), reached San Francisco, they head their way to [Mountain View](https://en.wikipedia.org/wiki/Mountain_View,_California) where global head-quarter of Google, [Googleplex](https://en.wikipedia.org/wiki/Googleplex) & [Shoreline Amphitheatre](https://en.wikipedia.org/wiki/Shoreline_Amphitheatre) are situated. Shoreline Amphitheatre is place where every year Google IO conference take place. During IO, Google converts whole amphitheatre & it's parking area into IO Venue.
> +
> + Countdown for Google IO conference began. Google IO is a three days event. At the first day in morning, they did breakfast at IO venue which was little bit strange for them but they told it was so good. After that, it was time for [keynote](https://www.theverge.com/2018/5/8/17320962/google-io-keynote-2018-announcements-news-android-p). They enjoyed amazing keynote lead by Sundar Pichai. Keynote continued for approximately two hours by different rocking speakers, speaking on upcoming innovative stuffs. It was fantasic experience for them. According to them, if an IO attendee could miss keynote & goes to back stage, he/she can definitely interact with Sundar Pichai & other speakers. After keynote, sessions on different technical stuffs started in the [codelabs](https://events.google.com/io/schedule/?section=may-8). Codelabs are small buildings where sessions on different tech-stuffs take place. There were codelabs for Android, Firebase, Web , Google Accessibility, Android & IoT, Machine Learning, Flutter and many more. Attendees can attend codelabs depending on their specific field of interest or they can even explore different stuffs. After one hour of codelabs, there was [Developer Keynote](https://events.google.com/io/schedule/?section=may-8), where speakers explained innovations in different development frameworks used for developing different products. This keynote too was a great experience for the co-organizers, by which developers can code efficient products. Keynote continued for one hour & again sessions in the codelabs began. And that codelab sessions were in motion on the second & third day of IO, for the whole day, starting from morning to evening. According to co-organizers, codelab can be a best thing to explore & learn different stuffs.
>
> Please break this into two paragraphs. Read "Updating PRs" sections of the
> contributing guide to see how to make updates to a PR.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gdgbaroda/gdgbaroda.github.io/pull/34#pullrequestreview-140144418>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AfE7PJgri9K6ZmR8nXjoG_ns2tIucvacks5uJ9qpgaJpZM4VbkYG>
> .
>

2018-07-25 12:55 UTC, manan-jadhav approved these changes

2018-07-25 12:55 UTC, merged