Add community guidelines for contributions
gdgbaroda/gdgbaroda.github.io pull request #37
Opened 2018-07-25 04:19 UTC by SnehPandya18

What does this PR add / remove or fix?
* Create Code of Conduct, Issue Template & Pull Request Template
* Update existing README with proper target links to the guides

Does this PR match the guidelines documented in the Contributing Guide?
* Yes

2018-07-25 12:55 UTC, CurosMJ commented
Please remove old PR template from contributing guide.

2018-07-25 13:05 UTC, manan-jadhav requested changes

2018-07-25 13:05 UTC, CurosMJ commented on CONTRIBUTING.md
> -### Create a Pull Request
This section needs to stay

2018-07-25 13:05 UTC, CurosMJ commented on CONTRIBUTING.md
> -## Writing Pull Requests
Add description that one should use the template provided, and link to the template. Keep this section also as it is being referenced from table of contents

2018-07-30 03:19 UTC, CurosMJ commented
@SnehPandya18 Please provide corrections so we can push this.

2018-07-31 13:31 UTC, SnehPandya18 commented
@CurosMJ the requested changes have been incorporated. Kindly have a look.

2018-07-31 14:03 UTC, manan-jadhav approved these changes

2018-07-31 14:03 UTC, merged